import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Check, RefreshCw, Workflow } from 'lucide-react';
import { Badge } from '../components/Badge';
import { api, type IncidentRow, type SessionUser } from '../shared';

type Playbook={key:string;name:string;description:string;steps:string[]};
type Run={id:number;incident_key:string;playbook_key:string;playbook:string;requested_by:number;steps:string[];status:string;execution_mode:string;approval_note:string;created_at:string};

export function AutomationPage({token,user}:{token:string;user:SessionUser}){
 const [runs,setRuns]=useState<Run[]>([]),[incidents,setIncidents]=useState<IncidentRow[]>([]),[playbooks,setPlaybooks]=useState<Playbook[]>([]),[incidentKey,setIncidentKey]=useState(''),[playbookKey,setPlaybookKey]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const canManage=user.permissions.includes('incidents:manage'),canApprove=user.permissions.includes('response:approve');
 const refresh=useCallback(async()=>{try{const [r,i,p]=await Promise.all([api<Run[]>('/automation/runs',token),api<IncidentRow[]>('/incidents',token),api<Playbook[]>('/response-playbooks',token)]);setRuns(r);setIncidents(i);setPlaybooks(p);setIncidentKey(current=>current||i[0]?.incident_key||'');setPlaybookKey(current=>current||p[0]?.key||'');setError('')}catch(e){setError(e instanceof Error?e.message:'Automation data could not be loaded')}},[token]);
 useEffect(()=>{void refresh()},[refresh]);
 async function createRun(e:FormEvent){e.preventDefault();if(!incidentKey||!playbookKey)return;setBusy(true);try{await api('/automation/runs',token,{method:'POST',body:JSON.stringify({incident_key:incidentKey,playbook_key:playbookKey})});await refresh()}catch(e){setError(e instanceof Error?e.message:'Run request failed')}finally{setBusy(false)}}
 async function decide(run:Run,decision:'Approved'|'Rejected'){const note=window.prompt(`Decision note for ${run.playbook}`)||'';setBusy(true);try{await api(`/automation/runs/${run.id}/decision`,token,{method:'POST',body:JSON.stringify({decision,note})});await refresh()}catch(e){setError(e instanceof Error?e.message:'Approval decision failed')}finally{setBusy(false)}}
 async function complete(run:Run){setBusy(true);try{await api(`/automation/runs/${run.id}/complete`,token,{method:'POST'});await refresh()}catch(e){setError(e instanceof Error?e.message:'Checklist completion failed')}finally{setBusy(false)}}
 return <><div className="page-head"><div><div className="eyebrow">GOVERNANCE / RESPONSE AUTOMATION</div><h1>Automation</h1><p className="subtitle">Request, approve and track incident response checklists from one workspace.</p></div><button className="button secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Refresh</button></div>{error&&<div className="admin-error">{error}</div>}{canManage&&<section className="panel admin-create"><h2>Start a response workflow</h2><p>All recipes run as manual checklists. The application does not execute changes in cloud, identity or endpoint systems.</p><form onSubmit={createRun}><select aria-label="Incident" value={incidentKey} onChange={e=>setIncidentKey(e.target.value)}>{incidents.map(i=><option key={i.incident_key} value={i.incident_key}>{i.incident_key} · {i.title}</option>)}</select><select aria-label="Response playbook" value={playbookKey} onChange={e=>setPlaybookKey(e.target.value)}>{playbooks.map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</select><button className="button primary" disabled={busy||!incidentKey||!playbookKey}><Workflow size={14}/> Request approval</button></form></section>}<section className="panel list-panel"><div className="panel-head"><div><h2>Workflow history</h2><p>{runs.length} recorded run{runs.length===1?'':'s'} across incidents.</p></div></div><div className="workflow-list">{runs.map(run=><article key={run.id}><div className="workflow-heading"><strong>{run.playbook}</strong><Badge tone={run.status==='Approved'||run.status==='Completed'?'blue':run.status==='Rejected'?'red':'amber'}>{run.status}</Badge></div><p><b>{run.incident_key}</b> · {new Date(run.created_at).toLocaleString()} · {run.execution_mode}</p><ol>{run.steps.map(step=><li key={step}>{step}</li>)}</ol>{run.approval_note&&<p>Decision note: {run.approval_note}</p>}{canApprove&&run.status==='Pending approval'&&<div className="dialog-actions"><button className="button secondary" disabled={busy||run.requested_by===user.id} onClick={()=>void decide(run,'Rejected')}>Reject</button><button className="button primary" disabled={busy||run.requested_by===user.id} onClick={()=>void decide(run,'Approved')}><Check size={14}/> Approve</button></div>}{canManage&&run.status==='Approved'&&<button className="button primary" disabled={busy} onClick={()=>void complete(run)}>Mark checklist complete</button>}</article>)}{runs.length===0&&<div className="empty-state"><Workflow size={22}/><strong>No automation runs</strong><span>Start a response workflow from an incident to create the first approval record.</span></div>}</div></section></>;
}
