import { useCallback, useEffect, useState } from 'react';
import { Copy, Network, Plus, RefreshCw, Slash } from 'lucide-react';
import { Badge } from '../components/Badge';
import { API, api } from '../shared';

type Integration = { id: number; name: string; provider: string; token_prefix?: string; is_active?: boolean; created_at?: string; last_ingested_at?: string | null; last_attempt_at?:string|null; last_error?:string|null; successful_batches?:number; failed_batches?:number; last_event_count?:number; health?:string; token?: string };
type IntegrationDiagnostic={name:string;health:string;database:string;stored_events:number;successful_batches:number;failed_batches:number;last_event_count:number;last_attempt_at:string|null;last_ingested_at:string|null;last_error:string|null};
export function IntegrationsPage({ token }: { token: string }) {
  const [items, setItems] = useState<Integration[]>([]); const [name, setName] = useState(''); const [provider, setProvider] = useState(''); const [created, setCreated] = useState<Integration | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);const [diagnostic,setDiagnostic]=useState<IntegrationDiagnostic|null>(null);
  const refresh = useCallback(async () => { try { setItems(await api<Integration[]>('/integrations', token)); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load integrations'); } }, [token]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const integration = await api<Integration>('/integrations', token, { method: 'POST', body: JSON.stringify({ name, provider }) }); setCreated(integration); setName(''); setProvider(''); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not create integration'); } finally { setBusy(false); } }
  async function toggle(item: Integration) { try { await api(`/integrations/${item.id}`, token, { method: 'PATCH', body: JSON.stringify({ is_active: !item.is_active }) }); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not update integration'); } }
  async function diagnose(item:Integration){setError('');try{setDiagnostic(await api<IntegrationDiagnostic>(`/integrations/${item.id}/diagnostics`,token))}catch(reason){setError(reason instanceof Error?reason.message:'Diagnostics could not be loaded')}}
  const sample = created?.token ? `curl -X POST "${API}/telemetry/ingest" \\\n  -H "Content-Type: application/json" \\\n  -H "X-Ingestion-Key: ${created.token}" \\\n  -d '{"events":[{"external_id":"evt-001","event_type":"detection","severity":"High","summary":"Suspicious access","asset":{"asset_key":"aws:prod-api-01","name":"prod-api-01","asset_type":"server","provider":"AWS","environment":"Production","criticality":"High","risk_score":78}}]}'` : '';
  return <>
    <div className="page-head"><div><div className="eyebrow">ADMINISTRATION / DATA CONNECTIONS</div><h1>Integrations</h1><p className="subtitle">Issue source-specific ingestion keys and normalize telemetry into alerts and assets.</p></div><button className="button secondary" onClick={() => void refresh()}><RefreshCw size={14}/> Refresh</button></div>
    {error && <div className="admin-error">{error}</div>}
    <section className="panel integration-create"><div><div className="eyebrow">NEW DATA SOURCE</div><h2>Connect an integration</h2><p>Each integration gets a unique ingestion key. The key is shown once at creation.</p></div><form onSubmit={(event) => void create(event)}><label>Integration name<input value={name} onChange={(event) => setName(event.target.value)} required minLength={2} maxLength={120} placeholder="e.g. aws-cloudtrail-prod"/></label><label>Provider<input value={provider} onChange={(event) => setProvider(event.target.value)} required minLength={2} maxLength={80} placeholder="e.g. AWS CloudTrail"/></label><button className="button primary" disabled={busy}><Plus size={14}/>{busy ? 'Creating…' : 'Create integration'}</button></form></section>
    {created?.token && <section className="panel token-reveal"><div><Badge tone="amber">Copy this key now</Badge><h2>{created.name} ingestion key</h2><p>For security, the raw key cannot be retrieved later. Create a replacement integration if it is lost.</p></div><code>{created.token}</code><h3>Example request</h3><pre>{sample}</pre><button className="button secondary" onClick={() => void navigator.clipboard?.writeText(sample)}><Copy size={14}/> Copy cURL example</button></section>}
    {diagnostic&&<section className="panel integration-diagnostic"><div className="panel-head"><div><h2>Diagnostics · {diagnostic.name}</h2><p>Database: {diagnostic.database} · Stored telemetry: {diagnostic.stored_events} events</p></div><button className="icon-btn" onClick={()=>setDiagnostic(null)}>×</button></div><div className="module-metrics">{[['Health',diagnostic.health],['Successful batches',diagnostic.successful_batches],['Failed batches',diagnostic.failed_batches],['Last batch events',diagnostic.last_event_count],['Last attempt',diagnostic.last_attempt_at?new Date(diagnostic.last_attempt_at).toLocaleString():'Never'],['Last success',diagnostic.last_ingested_at?new Date(diagnostic.last_ingested_at).toLocaleString():'Never']].map(([label,value])=><div className="panel module-stat" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{diagnostic.last_error&&<div className="admin-error">Latest error: {diagnostic.last_error}</div>}</section>}
    <section className="panel list-panel"><div className="panel-head"><div><h2>Configured sources</h2><p>Connector freshness is healthy for 15 minutes after a successful ingest; failed deliveries keep their diagnostic detail.</p></div></div><div className="table-wrap"><table><thead><tr>{['INTEGRATION','PROVIDER','KEY PREFIX','HEALTH','LAST SUCCESS','BATCHES','CREATED','ACTIONS'].map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><div className="incident-title"><span className="metric-icon blue"><Network size={14}/></span><div><strong>{item.name}</strong><small>Integration #{item.id}</small></div></div></td><td>{item.provider}</td><td><code>{item.token_prefix}••••••</code></td><td><Badge tone={item.health==='Healthy'?'blue':item.health==='Error'?'red':'amber'}>{item.health||'Waiting'}</Badge>{item.last_error&&<small className="table-sub">{item.last_error}</small>}</td><td>{item.last_ingested_at ? new Date(item.last_ingested_at).toLocaleString() : 'Never'}</td><td>{item.successful_batches||0} ok / {item.failed_batches||0} failed<br/><small className="table-sub">{item.last_event_count||0} events last batch</small></td><td>{item.created_at ? new Date(item.created_at).toLocaleDateString() : '—'}</td><td><div className="head-actions"><button className="button secondary" onClick={()=>void diagnose(item)}>Check</button><button className="button secondary" onClick={() => void toggle(item)}><Slash size={13}/>{item.is_active ? 'Revoke' : 'Activate'}</button></div></td></tr>)}</tbody></table>{items.length === 0 && <div className="empty-state"><Network size={24}/><strong>No integrations configured</strong><span>Create a source above, then send normalized events to the ingest endpoint.</span></div>}</div></section>
  </>;
}
