import { useCallback, useEffect, useState } from 'react';
import { Copy, Network, Plus, RefreshCw, Slash } from 'lucide-react';
import { Badge } from '../components/Badge';
import { API, api } from '../shared';

type Integration = { id: number; name: string; provider: string; token_prefix?: string; is_active?: boolean; created_at?: string; last_ingested_at?: string | null; token?: string };
export function IntegrationsPage({ token }: { token: string }) {
  const [items, setItems] = useState<Integration[]>([]); const [name, setName] = useState(''); const [provider, setProvider] = useState(''); const [created, setCreated] = useState<Integration | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { try { setItems(await api<Integration[]>('/integrations', token)); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load integrations'); } }, [token]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const integration = await api<Integration>('/integrations', token, { method: 'POST', body: JSON.stringify({ name, provider }) }); setCreated(integration); setName(''); setProvider(''); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not create integration'); } finally { setBusy(false); } }
  async function toggle(item: Integration) { try { await api(`/integrations/${item.id}`, token, { method: 'PATCH', body: JSON.stringify({ is_active: !item.is_active }) }); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not update integration'); } }
  const sample = created?.token ? `curl -X POST "${API}/telemetry/ingest" \\\n  -H "Content-Type: application/json" \\\n  -H "X-Ingestion-Key: ${created.token}" \\\n  -d '{"events":[{"external_id":"evt-001","event_type":"detection","severity":"High","summary":"Suspicious access","asset":{"asset_key":"aws:prod-api-01","name":"prod-api-01","asset_type":"server","provider":"AWS","environment":"Production","criticality":"High","risk_score":78}}]}'` : '';
  return <>
    <div className="page-head"><div><div className="eyebrow">ADMINISTRATION / DATA CONNECTIONS</div><h1>Integrations</h1><p className="subtitle">Issue source-specific ingestion keys and normalize telemetry into alerts and assets.</p></div><button className="button secondary" onClick={() => void refresh()}><RefreshCw size={14}/> Refresh</button></div>
    {error && <div className="admin-error">{error}</div>}
    <section className="panel integration-create"><div><div className="eyebrow">NEW DATA SOURCE</div><h2>Connect an integration</h2><p>Each integration gets a unique ingestion key. The key is shown once at creation.</p></div><form onSubmit={(event) => void create(event)}><label>Integration name<input value={name} onChange={(event) => setName(event.target.value)} required minLength={2} maxLength={120} placeholder="e.g. aws-cloudtrail-prod"/></label><label>Provider<input value={provider} onChange={(event) => setProvider(event.target.value)} required minLength={2} maxLength={80} placeholder="e.g. AWS CloudTrail"/></label><button className="button primary" disabled={busy}><Plus size={14}/>{busy ? 'Creating…' : 'Create integration'}</button></form></section>
    {created?.token && <section className="panel token-reveal"><div><Badge tone="amber">Copy this key now</Badge><h2>{created.name} ingestion key</h2><p>For security, the raw key cannot be retrieved later. Create a replacement integration if it is lost.</p></div><code>{created.token}</code><h3>Example request</h3><pre>{sample}</pre><button className="button secondary" onClick={() => void navigator.clipboard?.writeText(sample)}><Copy size={14}/> Copy cURL example</button></section>}
    <section className="panel list-panel"><div className="panel-head"><div><h2>Configured sources</h2><p>Last received timestamp confirms the connector is sending data.</p></div></div><div className="table-wrap"><table><thead><tr>{['INTEGRATION','PROVIDER','KEY PREFIX','STATUS','LAST INGESTED','CREATED','ACTION'].map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><div className="incident-title"><span className="metric-icon blue"><Network size={14}/></span><div><strong>{item.name}</strong><small>Integration #{item.id}</small></div></div></td><td>{item.provider}</td><td><code>{item.token_prefix}••••••</code></td><td><Badge tone={item.is_active ? 'blue' : 'red'}>{item.is_active ? 'Active' : 'Inactive'}</Badge></td><td>{item.last_ingested_at ? new Date(item.last_ingested_at).toLocaleString() : 'Waiting for events'}</td><td>{item.created_at ? new Date(item.created_at).toLocaleDateString() : '—'}</td><td><button className="button secondary" onClick={() => void toggle(item)}><Slash size={13}/>{item.is_active ? 'Revoke key' : 'Activate'}</button></td></tr>)}</tbody></table>{items.length === 0 && <div className="empty-state"><Network size={24}/><strong>No integrations configured</strong><span>Create a source above, then send normalized events to the ingest endpoint.</span></div>}</div></section>
  </>;
}
