import { useCallback, useEffect, useState } from 'react';
import { Activity, Braces, Check, CircleAlert, Code2, Pencil, Play, Plus, RefreshCw, Shield, Trash2, X } from 'lucide-react';
import { Badge } from '../components/Badge';
import { api } from '../shared';

type YaraRule={id:number;name:string;namespace:string;description:string;source:string;severity:string;enabled:boolean;created_at:string;updated_at:string};
type Simulation={rule:string;examined:number;matched:number;sample:{source:string;key:string;event_type:string;severity:string;summary:string;matched_strings:string[]}[];simulated_at:string};
const starter=`rule Suspicious_PowerShell_Encoded_Command {
  meta:
    description = "Finds encoded PowerShell execution in telemetry"
    author = "CipherOps SOC"
    severity = "High"
  strings:
    $shell = "powershell" nocase
    $encoded = "-enc" nocase
    $encoded_long = "-encodedcommand" nocase
  condition:
    $shell and ($encoded or $encoded_long)
}`;

export function YaraRulesPage({token,canManage}:{token:string;canManage:boolean}){
 const [rules,setRules]=useState<YaraRule[]>([]),[name,setName]=useState(''),[description,setDescription]=useState(''),[namespace,setNamespace]=useState('cipherops'),[severity,setSeverity]=useState('High'),[source,setSource]=useState(starter),[editingId,setEditingId]=useState<number|null>(null),[simulation,setSimulation]=useState<Simulation|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const refresh=useCallback(async()=>{try{setRules(await api<YaraRule[]>('/yara-rules',token));setError('')}catch(e){setError(e instanceof Error?e.message:'YARA library could not be loaded')}},[token]);
 useEffect(()=>{void refresh()},[refresh]);
 async function create(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setSaved(false);try{const body=JSON.stringify({name,namespace,description,source,severity});if(editingId)await api(`/yara-rules/${editingId}`,token,{method:'PATCH',body});else await api('/yara-rules',token,{method:'POST',body});setName('');setDescription('');setNamespace('cipherops');setSeverity('High');setSource(starter);setEditingId(null);setSaved(true);await refresh()}catch(e){setError(e instanceof Error?e.message:'YARA rule could not be compiled and saved')}finally{setBusy(false)}}
 function edit(rule:YaraRule){setEditingId(rule.id);setName(rule.name);setNamespace(rule.namespace);setDescription(rule.description);setSeverity(rule.severity);setSource(rule.source);setSaved(false);window.scrollTo({top:0,behavior:'smooth'})}
 function cancelEdit(){setEditingId(null);setName('');setNamespace('cipherops');setDescription('');setSeverity('High');setSource(starter)}
 async function toggle(rule:YaraRule){try{await api(`/yara-rules/${rule.id}`,token,{method:'PATCH',body:JSON.stringify({enabled:!rule.enabled})});await refresh()}catch(e){setError(e instanceof Error?e.message:'YARA rule status could not be changed')}}
 async function simulate(rule:YaraRule){setSimulation(null);setError('');try{setSimulation(await api<Simulation>(`/yara-rules/${rule.id}/simulate`,token,{method:'POST'}))}catch(e){setError(e instanceof Error?e.message:'YARA simulation failed')}}
 async function remove(rule:YaraRule){if(!window.confirm(`Delete YARA rule “${rule.name}”?`))return;try{await api(`/yara-rules/${rule.id}`,token,{method:'DELETE'});if(simulation?.rule===rule.name)setSimulation(null);await refresh()}catch(e){setError(e instanceof Error?e.message:'YARA rule could not be deleted')}}
 const enabled=rules.filter(rule=>rule.enabled).length;
 return <div className="yara-page"><div className="page-head"><div><div className="eyebrow">SECURITY / DETECTION ENGINEERING</div><h1>YARA Rules</h1><p className="subtitle">Compile YARA rules, simulate them against recent telemetry and detect matching events during ingest.</p></div><button className="button secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Refresh</button></div>{error&&<div className="admin-error"><CircleAlert size={15}/>{error}</div>}{saved&&<div className="yara-success"><Check size={15}/> Rule compiled successfully and added to the library.</div>}
 <div className="yara-summary"><article className="panel"><span className="yara-summary-icon"><Braces size={17}/></span><div><small>YARA rules</small><strong>{rules.length}</strong></div></article><article className="panel"><span className="yara-summary-icon active"><Activity size={17}/></span><div><small>Enabled at ingest</small><strong>{enabled}</strong></div></article><article className="panel"><span className="yara-summary-icon"><Shield size={17}/></span><div><small>Engine</small><strong>YARA 4.x</strong></div></article></div>
 <div className="yara-layout">{canManage&&<section className="panel yara-editor"><div className="panel-head"><div><div className="eyebrow">RULE AUTHORING</div><h2>{editingId?'Edit YARA rule':'Create a YARA rule'}</h2><p>Rules compile before saving. A valid rule can be simulated against the latest 500 events.</p></div><span className="yara-code-mark"><Code2 size={17}/></span></div><form onSubmit={e=>void create(e)}><div className="dialog-fields"><label>Rule name<input required minLength={3} maxLength={160} value={name} onChange={e=>setName(e.target.value)} placeholder="Suspicious_PowerShell"/></label><label>Namespace<input required pattern="[A-Za-z_][A-Za-z0-9_]*" value={namespace} onChange={e=>setNamespace(e.target.value)} placeholder="cipherops"/></label></div><label>Description<input maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What behavior does this rule detect?"/></label><div className="dialog-fields"><label>Alert severity<select value={severity} onChange={e=>setSeverity(e.target.value)}>{['Critical','High','Medium','Low','Informational'].map(value=><option key={value}>{value}</option>)}</select></label><label>Rule format<span className="yara-format"><Braces size={14}/> Native YARA source</span></label></div><label>YARA source<textarea className="yara-source" spellCheck={false} required minLength={20} maxLength={32000} value={source} onChange={e=>setSource(e.target.value)} /></label><div className="yara-actions"><button className="button primary" disabled={busy}><Plus size={14}/>{busy?'Compiling…':editingId?'Compile and update rule':'Compile and save rule'}</button>{editingId&&<button type="button" className="button secondary" onClick={cancelEdit}><X size={14}/> Cancel</button>}</div></form></section>}
 <section className="panel list-panel yara-library"><div className="panel-head"><div><div className="eyebrow">RULE LIBRARY</div><h2>Saved rules</h2><p>Enabled rules run against each telemetry event as it is ingested.</p></div><span className="metric-icon blue"><Braces size={16}/></span></div><div className="yara-rule-list">{rules.map(rule=><article className="yara-rule" key={rule.id}><div className="yara-rule-head"><span className="yara-rule-icon"><Braces size={16}/></span><div className="yara-rule-title"><strong>{rule.name}</strong><small>{rule.namespace} · {rule.description||'No description'}</small></div><Badge tone={rule.enabled?'blue':'amber'}>{rule.enabled?'Enabled':'Disabled'}</Badge></div><div className="yara-rule-meta"><span>Severity <Badge tone={rule.severity==='Critical'?'red':rule.severity==='High'?'amber':'blue'}>{rule.severity}</Badge></span><span><Code2 size={13}/> YARA source · {rule.source.split('\n').length} lines</span></div><pre className="yara-preview">{rule.source}</pre><div className="yara-actions"><button className="button secondary" onClick={()=>void simulate(rule)}><Play size={13}/> Simulate</button>{canManage&&<><button className="button secondary" onClick={()=>edit(rule)}><Pencil size={13}/> Edit</button><button className="button secondary" onClick={()=>void toggle(rule)}>{rule.enabled?'Disable':'Enable'}</button><button className="button secondary danger-button" onClick={()=>void remove(rule)}><Trash2 size={13}/> Delete</button></>}</div></article>)}{!rules.length&&<div className="empty-state"><Braces size={22}/><strong>No YARA rules configured</strong><span>{canManage?'Compile and save the first rule to get started.':'Ask a detection manager to add a rule.'}</span></div>}</div></section></div>
 {simulation&&<section className="panel yara-simulation"><div className="panel-head"><div><div className="eyebrow">TELEMETRY SIMULATION</div><h2>{simulation.rule}</h2><p>{simulation.matched} matched of {simulation.examined} events checked · {new Date(simulation.simulated_at).toLocaleString()}</p></div><button className="icon-btn" aria-label="Close simulation" onClick={()=>setSimulation(null)}>×</button></div><div className="table-wrap"><table><thead><tr>{['SOURCE','EVENT ID','SEVERITY','MATCHED STRINGS','SUMMARY'].map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{simulation.sample.map(row=><tr key={`${row.source}-${row.key}`}><td>{row.source}</td><td>{row.key}</td><td>{row.severity}</td><td>{row.matched_strings.join(', ')}</td><td>{row.summary}</td></tr>)}</tbody></table>{!simulation.sample.length&&<div className="empty-state">No matching events in the latest {simulation.examined} telemetry records.</div>}</div></section>}</div>
}
