import { LayoutDashboard, Siren, Bell, Crosshair, Bug, Boxes, Fingerprint, Cloud, Sparkles, ShieldCheck, FileClock, Command, Users, Settings, Network } from 'lucide-react';

export type Page='Dashboard'|'Incidents'|'Alerts'|'Threat Intelligence'|'Vulnerabilities'|'Assets'|'Identity Security'|'Cloud Security'|'AI Agent Security'|'Compliance'|'Reports'|'Automation'|'Settings'|'Users'|'Roles'|'Audit Logs'|'Integrations';
export type SessionUser={id:number;email:string;full_name:string;first_name?:string;last_name?:string;phone_country?:string|null;phone_dial_code?:string|null;mobile_number?:string|null;country_code?:string|null;country?:string|null;city?:string|null;avatar_data?:string|null;roles:string[];permissions:string[]};
export type IncidentRow={incident_key:string;title:string;severity:string;risk_score:number;status:string;source:string;asset_count:number;owner:string;created_at:string};
export const navigation:{name:Page;icon:any;group:string}[]=[{name:'Dashboard',icon:LayoutDashboard,group:'OPERATIONS'},{name:'Incidents',icon:Siren,group:'OPERATIONS'},{name:'Alerts',icon:Bell,group:'OPERATIONS'},{name:'Threat Intelligence',icon:Crosshair,group:'OPERATIONS'},{name:'Vulnerabilities',icon:Bug,group:'OPERATIONS'},{name:'Assets',icon:Boxes,group:'OPERATIONS'},{name:'Identity Security',icon:Fingerprint,group:'SECURITY'},{name:'Cloud Security',icon:Cloud,group:'SECURITY'},{name:'AI Agent Security',icon:Sparkles,group:'SECURITY'},{name:'Compliance',icon:ShieldCheck,group:'GOVERNANCE'},{name:'Reports',icon:FileClock,group:'GOVERNANCE'},{name:'Automation',icon:Command,group:'GOVERNANCE'},{name:'Users',icon:Users,group:'ADMINISTRATION'},{name:'Roles',icon:ShieldCheck,group:'ADMINISTRATION'},{name:'Audit Logs',icon:FileClock,group:'ADMINISTRATION'},{name:'Integrations',icon:Network,group:'ADMINISTRATION'},{name:'Settings',icon:Settings,group:'ADMINISTRATION'}];
export const API=(import.meta as any).env?.VITE_API_URL||'http://localhost:8000/api/v1';
export async function api<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const response=await fetch(`${API}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...init.headers}});if(!response.ok){if(response.status===401)window.dispatchEvent(new Event('cipherops:unauthorized'));const payload=await response.json().catch(()=>({}));throw new Error(payload.detail||`Request failed (${response.status})`)}return response.json() as Promise<T>}

export async function imageToAvatar(file:File):Promise<string>{if(!file.type.startsWith('image/'))throw new Error('Choose an image file.');if(file.size>8*1024*1024)throw new Error('Choose an image smaller than 8 MB.');const bitmap=await createImageBitmap(file);const size=Math.min(bitmap.width,bitmap.height,384),sx=Math.max(0,(bitmap.width-size)/2),sy=Math.max(0,(bitmap.height-size)/2),canvas=document.createElement('canvas');canvas.width=384;canvas.height=384;const context=canvas.getContext('2d');if(!context)throw new Error('Could not process this image.');context.drawImage(bitmap,sx,sy,size,size,0,0,384,384);bitmap.close();return canvas.toDataURL('image/jpeg',.82)}
